#pragma once
#include <unordered_map>
#include <string>

namespace MikuMikuWorld
{
	extern std::unordered_map<std::string, std::string> en{
		// menu bar
		{"file", "File"},
		{"new", "New"},
		{"open", "Open"},
		{"save", "Save"},
		{"save_as", "Save As"},
		{"export", "Export"},
		{"exit", "Exit"},
		{"edit", "Edit"},
		{"undo", "Undo"},
		{"redo", "Redo"},
		{"select_all", "Select All"},
		{"settings", "Settings"},
		{"window", "Window"},
		{"vsync", "VSync"},
		{"show_performance", "Show Performance Metrics"},
		{"debug", "Debug"},
		{"create_auto_save", "Create Auto Save"},
		{"about", "About"},

		// dialogs
		{"unsaved_changes", "Unsaved Changes"},
		{"ask_save", "Save current changes?"},
		{"warn_unsaved", "Any unsaved changes will be lost."},
		{"save_changes", "Save Changes"},
		{"discard_changes", "Discard Changes"},
		{"cancel", "Cancel"},
		{"auto_save", "Auto Save"},
		{"auto_save_enable", "Auto Save Enabled"},
		{"auto_save_interval", "Auto Save Interval (min)"},
		{"auto_save_count", "Maximum Auto Save Entries"},
		{"accent_color", "Accent Color"},
		{"accent_color_help", "Select an accent color to apply. The first slot can be customized from the color controls below."},
		{"select_accent_color", "Select an accent color."},
		{"display_mode", "Display Mode"},
		{"custom_color", "Custom Color"},
		{"timeline", "Timeline"},
		{"lane_width", "Lane Width"},
		{"notes_height", "Notes Height"},
		{"use_smooth_scroll", "Use Smooth Scrolling"},
		{"smooth_scroll_time", "Smooth Scrolling Time"},
		{"video", "Video"},
		{"vsync_enable", "Enable VSync"},

		// score editor
		{"toolbox", "Toolbox"},
		{"controls", "Controls"},
		{"chart_properties", "Chart Properties"},
		{"notes_timeline", "Notes Timeline"},
		{"select", "Select"},
		{"tap", "Tap"},
		{"hold", "Hold"},
		{"hold_step", "Hold Mid"},
		{"flick", "Flick"},
		{"critical", "Critical"},
		{"bpm", "BPM"},
		{"time_signature", "Time Signature"},
		{"none", "None"},
		{"page", "Page"},
		{"follow_cursor", "Follow Cursor"},
		{"up", "Up"},
		{"left", "Left"},
		{"right", "Right"},
		{"visible", "Visible"},
		{"invisible", "Invisible"},
		{"ignored", "Ignored"},
		{"linear", "Linear"},
		{"ease_in", "Ease-In"},
		{"ease_out", "Ease-Out"},
		{"delete", "Delete"},
		{"copy", "Copy"},
		{"paste", "Paste"},
		{"flip_paste", "Flip Paste"},
		{"flip", "Flip"},
		{"note_width", "Note Width"},
		{"shrink_down", "Shrink To First"},
		{"shrink_up", "Shrink To Last"},
		{"step_type", "Step Type"},
		{"ease_type", "Ease Type"},
		{"flick_type", "Flick Type"},
		{"metadata", "Metadata"},
		{"title", "Title"},
		{"designer", "Designer"},
		{"artist", "Artist"},
		{"jacket", "Jacket"},
		{"audio", "Audio"},
		{"music_file", "Music File"},
		{"music_offset", "Music Offset"},
		{"volume_master", "Master Volume"},
		{"volume_bgm", "BGM Volume"},
		{"volume_se", "SE Volume"},
		{"statistics", "Statistics"},
		{"taps", "Taps"},
		{"flicks", "Flicks"},
		{"holds", "Holds"},
		{"steps", "Hold Mids"},
		{"total", "Total"},
		{"combo", "Combo"},
		{"goto_measure", "Go To Measure"},
		{"division", "Division"},
		{"division_suffix", " Divison"},
		{"custom", "Custom "},
		{"custom_division", "Custom Division"},
		{"scroll_mode", "Scroll Mode"},
		{"zoom", "Zoom"},
		{"show_step_outlines", "Show Step Outlines"},
		{"edit_bpm", "Edit Tempo"},
		{"tick", "Tick"},
		{"remove", "Remove"},
		{"edit_time_signature", "Edit Time Signature"},
		{"measure", "Measure"},
		{"skill", "Skill"},

		// preset manager
		{"presets", "Presets"},
		{"no_presets", "No presets available"},
		{"name", "Name"},
		{"description", "Description"},
		{"create_preset", "Create Preset"},
		{"search", "Search..."}
	};
}
