#pragma once
#include "ScoreSerializer.h"
#include "Application.h"

namespace MikuMikuWorld
{
	class Note;
	class SUSNote;
	class SUS;

	class SusSerializer : public ScoreSerializer
	{
		std::string exportComment;

		std::pair<int, int> barLengthToFraction(float length, float fractionDenom);
		std::string noteKey(const SUSNote& note);
		std::string noteKey(const Note& note);

		Score susToScore(const SUS& sus);
		SUS scoreToSus(const Score& score);

	public:
		SusSerializer()
		{
			exportComment = "This file was generated by " APP_NAME " " + Application::getAppVersion();
		}

		void serialize(const Score& score, std::string filename) override;
		Score deserialize(std::string filename) override;
	};
}

